Fix crash when drawing outside top canvas border
stippi/WonderBrush-v2 pull request #26
Opened 2021-02-27 10:13 UTC by humdingerb

Only 64bit build was suffering that crash apparently.
Patch provided by nephele.

2021-02-27 14:01 UTC, stippi requested changes

2021-02-27 14:01 UTC, stippi commented on WonderBrush/src/tools/PenStroke.cpp
> +		return;
This doesn't seem right. From what I remember, `x` and `y` specify the center of the shape that is to be rendered by the `PenStroke`. The `constrainRect` should contain the necessary clipping. If somehow it is possible to render outside the bitmap buffer, then the bug is certainly not at this place. And if it were, then we should just as well check for `x < 0` and also right and bottom buffer bounds.

2021-02-27 14:23 UTC, stippi commented
I can reproduce the bug. Looking into it.

2021-02-27 14:56 UTC, stippi commented
Fixed by https://github.com/stippi/WonderBrush-v2/commit/b8c8f0d9cba3d194cb32dcbac41960a4b113c83b

2021-02-27 14:56 UTC, closed without merging

2021-02-27 16:26 UTC, humdingerb commented
Thanks for the quick investigation and fix! Should I update the haikuports recipe to publish the fixed version, or do you have other commits lined up that should be merged first?

2021-02-27 20:45 UTC, stippi commented
I have nothing else lined up for WB 2, sorry. Publishing this fixed version is much appreciated!

2021-02-28 07:33 UTC, humdingerb commented
I'll wait on your thoughts on #27. :)